In [1]:
from typing import Dict
import logging
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
#array representation
obj.array
#default index: array from 0 through n-1
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
#we can create a series with an index identifying a data point as a label
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [5]:
#view the index of obj2
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [6]:
obj2.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [7]:
#use index labels to select single values or a set of values
obj2['a']

-5

In [8]:
obj2["d"] = 6

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
#using numpy functions or numpy-like operations preserves the index/value link
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
#series as fixed-length ordered dictionaries
#create a series using a dictionary
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [14]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
#convert back to dict with the to_dict method
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
#key insertion order is preserved, to alter this, you can specifiy a dictionary
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [19]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
#The above example includes an nan value
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
#series can call these as instance methods
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
#series arithmetic
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
#name attribute can be used to create a pandas column name
obj4.name = 'population'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
#series's index can be altered in place by assignment
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [30]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [32]:
#pd.DataFrame: it is the pandas equivalent of a spreadsheet: a rectangular 2-dimensional table of data.
#row index and column index

In [33]:
#passing a dictionary of equal-length lists or numpy arrays
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.3]}
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.3

In [35]:
#first five rows
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
#last five rows
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.3

In [37]:
#create without specified sequence of columns
pd.DataFrame(data)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.3

In [38]:
#create with specified sequence of columns
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.3

In [39]:
#create a new empty column filled with np.nan values
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])

In [40]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.3  NaN

In [41]:
#we can set a scalar value to fill a column
frame2['debt'] = 16.5

In [42]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.3  16.5

In [43]:
#we can also use a numpy series
frame2['debt'] = np.arange(6.)

In [44]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.3   5.0

In [45]:
#when we assign lists or to a column, the length must match exactly
#if we assign a series, then its labels will be realigned exactly to the frame's index
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [46]:
frame2['debt'] = val

In [47]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.3   NaN

In [48]:
#assigning a column that does not exist will create a new column
#del keyword will delete columns like in a dictionary
frame2['eastern'] = frame2['state'] == 'Ohio'

In [49]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.3   NaN    False

In [50]:
#new columns cannot be created with the frame2.eastern dot attribute notation
frame2.western = frame2['state'] = 'Nevada'
#nothing happens

In [51]:
del frame2['eastern']

In [52]:
frame2

year   state  pop  debt
0  2000  Nevada  1.5   NaN
1  2001  Nevada  1.7   NaN
2  2002  Nevada  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.3   NaN

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
#column returned from indexing a dataframe is a view on underlying data, not a copy
#nested dictionary of dictionaries
#! ipython id=0b3c30df8ab14ab1a3486d88b9f23890
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [55]:
frame3 = pd.DataFrame(populations)

In [56]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [57]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [58]:
pd.DataFrame(populations)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [59]:
pd.DataFrame(populations, index=np.arange(2001, 2004))

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [60]:
pd.DataFrame(populations, index=pd.Index(np.arange(2001, 2004)))

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [61]:
pdata: Dict = {'Ohio': frame3['Ohio'][:-1],
              'Nevada': frame3['Nevada'][:2]}

/var/folders/kz/gdzfkm910wq4p613kw6rbgw40000gn/T/ipykernel_1294/1761938029.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  pdata: Dict = {'Ohio': frame3['Ohio'][:-1],
/var/folders/kz/gdzfkm910wq4p613kw6rbgw40000gn/T/ipykernel_1294/1761938029.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  'Nevada': frame3['Nevada'][:2]}


In [62]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [63]:
#2d ndarray
arr0 = np.random.rand(24).reshape(6, 4)
#calling reshape with the opposite dimensions is equivalent to calling transpose or .T
arr1 = arr0.reshape(4, 6)
arr0

array([[0.26318368, 0.35692371, 0.81678319, 0.96740114],
       [0.55683677, 0.23434708, 0.71499418, 0.75636748],
       [0.26247335, 0.95132678, 0.41269916, 0.29532303],
       [0.1685803 , 0.79785475, 0.85058744, 0.9235576 ],
       [0.67404911, 0.52753534, 0.0117026 , 0.21485491],
       [0.43290227, 0.2871201 , 0.40022715, 0.74791794]])

In [64]:
arr1.all() == arr0.T.all()

True

In [65]:
arr0.T

array([[0.26318368, 0.55683677, 0.26247335, 0.1685803 , 0.67404911,
        0.43290227],
       [0.35692371, 0.23434708, 0.95132678, 0.79785475, 0.52753534,
        0.2871201 ],
       [0.81678319, 0.71499418, 0.41269916, 0.85058744, 0.0117026 ,
        0.40022715],
       [0.96740114, 0.75636748, 0.29532303, 0.9235576 , 0.21485491,
        0.74791794]])

In [66]:
#numpy structured array
structured_arr0 = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
structured_arr0

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [67]:
#pass structured array to dataframe constructor
pd.DataFrame(structured_arr0)

name  age  weight
0   Rex    9    81.0
1  Fido    3    27.0

In [68]:
#pass structured array to dataframe constructor with columns out of order
pd.DataFrame(structured_arr0, columns=['age', 'name', 'weight'])

age  name  weight
0    9   Rex    81.0
1    3  Fido    27.0

In [69]:
#pass structured array to dataframe constructor with columns out of order
new_df = pd.DataFrame(structured_arr0, columns=['age', 'name', 'weight2']) #has a Nan value
new_df['weight2'] = structured_arr0['weight']
new_df

age  name  weight2
0    9   Rex     81.0
1    3  Fido     27.0

In [70]:
#pass structured array to dataframe constructor with columns out of order
pd.DataFrame(structured_arr0, ) #has a Nan value

name  age  weight
0   Rex    9    81.0
1  Fido    3    27.0

In [71]:
#list of series
new_df_series0 = [new_df[columnName] for columnName in new_df.columns]
new_df_series0

[0    9
 1    3
 Name: age, dtype: int32,
 0     Rex
 1    Fido
 Name: name, dtype: object,
 0    81.0
 1    27.0
 Name: weight2, dtype: float32]

In [72]:
#create a DataFrame from a list of Series
pd.DataFrame(new_df_series0) #each item becomes a row

0     1
age         9     3
name      Rex  Fido
weight2  81.0  27.0

In [73]:
#create a DataFrame from a list of Series
pd.DataFrame(new_df_series0, index=['age', 'name', 'weight2']) #same as specifying this as the Index

0     1
age         9     3
name      Rex  Fido
weight2  81.0  27.0

In [74]:
#create a DataFrame from a list of Series
pd.DataFrame(new_df_series0, index=np.arange(3)) #same as specifying this as the Index

0     1
0     9     3
1   Rex  Fido
2  81.0  27.0

In [75]:
#create a DataFrame from a list of Series
pd.DataFrame(new_df_series0, columns=np.arange(3)) #same as specifying this as the Index

0     1   2
age       9.0   3.0 NaN
name      Rex  Fido NaN
weight2  81.0  27.0 NaN

In [76]:
pd.DataFrame(new_df_series0, columns=['age', 'name', 'weight2']) #nothing is there

age  name  weight2
age      NaN   NaN      NaN
name     NaN   NaN      NaN
weight2  NaN   NaN      NaN

In [77]:
pd.DataFrame(new_df_series0, columns=np.arange(3)) #nothing is there

0     1   2
age       9.0   3.0 NaN
name      Rex  Fido NaN
weight2  81.0  27.0 NaN

In [78]:
#help(pd.DataFrame)

In [79]:
from dataclasses import make_dataclass
Point = make_dataclass("Point", [('x', int), ('y', int)])
pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])

x  y
0  0  0
1  0  3
2  2  3

In [80]:
Pet = make_dataclass("Pet", [('age', float), ('name', str), ('weight', float)])
pd.DataFrame([Pet(9., 'Rex', 81.), Pet(3.0, 'Fido', 27.0)])

age  name  weight
0  9.0   Rex    81.0
1  3.0  Fido    27.0

In [81]:
#another DataFrame
Pet = make_dataclass("Pet", [('age', float), ('name', str), ('weight', float)])
pd.DataFrame(pd.DataFrame([Pet(9., 'Rex', 81.), Pet(3.0, 'Fido', 27.0)]))
#same as above, adding an existing DataFrame creates a new DataFrame with the same items

age  name  weight
0  9.0   Rex    81.0
1  3.0  Fido    27.0

In [82]:
#another DataFrame
Pet = make_dataclass("Pet", [('age', float), ('name', str), ('weight', float)])
pd.DataFrame(pd.DataFrame([Pet(9., 'Rex', 81.), Pet(3.0, 'Fido', 27.0)]),
            columns=['age', 'name', 'weight', 'owner name'])
#same as above, adding an existing DataFrame creates a new DataFrame with the same items

age  name  weight  owner name
0  9.0   Rex    81.0         NaN
1  3.0  Fido    27.0         NaN

In [83]:
#DataFrames have "index" and "columns" attributes that can have a name
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [84]:
frame3.index.name = 'year'

In [85]:
frame3.columns.name = 'state'

In [86]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [87]:
#DataFrames do not have a name attribute
hasattr(frame3, 'name')

False

In [88]:
#contrast this with something we know they do have: columns
hasattr(frame3, 'columns')

True

In [89]:
frame3['Ohio'].name

'Ohio'

In [90]:
hasattr(frame3['Ohio'], 'name')

True

In [91]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [92]:
frame3.iloc[0]

state
Ohio      1.5
Nevada    NaN
Name: 2000, dtype: float64

In [93]:
#Return data from DataFrame as two-dimensional numpy array
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [94]:
#the dtype chosen will be compatible with all columns
frame2.to_numpy()

array([[2000, 'Nevada', 1.5, nan],
       [2001, 'Nevada', 1.7, nan],
       [2002, 'Nevada', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.3, nan]], dtype=object)

In [95]:
#index objects
#an index holds an axis label and other metadata like the axis name
#Pandas converts any array of labels into an index
obj = pd.Series(np.arange(3))
obj
#here we use the existing values as an index

0    0
1    1
2    2
dtype: int64

In [96]:
#index objects
#an index holds an axis label and other metadata like the axis name
#Pandas converts any array of labels into an index
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])
obj
#here we specify existing values

a    0
b    1
c    2
dtype: int64

In [97]:
index = obj.index

In [98]:
index

Index(['a', 'b', 'c'], dtype='object')

In [99]:
index[1:]

Index(['b', 'c'], dtype='object')

In [100]:
#we cannot modify indexes as the user
try:
    index[1] = 'd'
except Exception as e:
    logging.warning(e)

In [101]:
#we cannot modify indexes as the user, changed to warning mode
try:
    index[1] = 'd'
except Exception as e:
    print(e)

Index does not support mutable operations


In [102]:
#we cannot modify indexes as the user, changed to critical mode
try:
    index[1] = 'd'
except Exception as e:
    logging.critical(e)

CRITICAL:root:Index does not support mutable operations


In [103]:
#we can use slicing on an index
index[1:]

Index(['b', 'c'], dtype='object')

In [104]:
index[1:]+index[0] #adds to both

Index(['ba', 'ca'], dtype='object')

In [105]:
index[1:].append(pd.Index([index[0]])) #we can append the first item and create a new index

Index(['b', 'c', 'a'], dtype='object')

In [106]:
one_onwards = index[1:]
zero_index = index[0]

one_onwards.append(pd.Index(list(zero_index))) #we can append the first item and create a new index

Index(['b', 'c', 'a'], dtype='object')

In [107]:
#immutability means we can share index objects among different data structures
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [108]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [109]:
#let's do this again but with floats
labels_for_floats = pd.Index(np.arange(3.)) #float index
#labels
obj2_floats = pd.Series([1.5, -2.5, 0], index=labels_for_floats)
obj2_floats

0.0    1.5
1.0   -2.5
2.0    0.0
dtype: float64

In [110]:
#immutability means we can share index objects among different data structures
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [111]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [112]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [113]:
obj2.index is labels

True

In [114]:
#indexes are also kind of like sets with a specified length
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [115]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [116]:
'Ohio' in frame3.columns

True

In [117]:
2003 in frame3.index

False

In [118]:
#the difference between sets and pd.Index objects is indexes can contain duplicate labels
pd.Index(['foo', 'foo', 'bar', 'bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [119]:
#index methods:
#append
foo_bar_values = ['foo']*2+['bar']*2
foo_bar_index0 = pd.Index(foo_bar_values)
foo_bar_index0

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [120]:
#index methods:
#append
foo_bar_values = ['foo']*2+['bar']*2
pd.Index(foo_bar_values).append(pd.Index(['foo']))

Index(['foo', 'foo', 'bar', 'bar', 'foo'], dtype='object')

In [121]:
#index methods:
#append
foo_bar_values = ['foo']*2+['bar']*2
new_index = pd.Index(foo_bar_values).append(pd.Index(['foo']))

In [124]:
#difference
new_index.difference(foo_bar_index0)

Index([], dtype='object')

In [125]:
#difference
foo_bar_index0.difference(new_index)

Index([], dtype='object')

In [132]:
foo_bar_index1 = foo_bar_index0.insert(-1, 'test')

In [134]:
foo_bar_index1 #inserts the item one short of the last slot

Index(['foo', 'foo', 'bar', 'test', 'bar'], dtype='object')

In [135]:
#drop()
foo_bar_index1.drop('test')

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [136]:
#is_monotonic_increasing
foo_bar_index1.is_monotonic_increasing

False

In [138]:
arange_index0 = pd.Index(np.arange(10.))
arange_index0.is_monotonic_increasing

True