In [1]:
from typing import List
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

In [2]:
train = pd.read_csv('datasets/titanic/train.csv')

In [3]:
test = pd.read_csv('datasets/titanic/test.csv')

In [4]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
#libraries like statsmodels and scikit-learn cannot be fed missing data in most cases, so lets
#see how much is missing

train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
#impute age by median
impute_value = train['Age'].median()

In [8]:
train['Age'].value_counts(dropna=False) 

NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ... 
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: Age, Length: 89, dtype: int64

In [9]:
test['Age'].value_counts(dropna=False)

NaN     86
24.0    17
21.0    17
22.0    16
30.0    15
        ..
76.0     1
28.5     1
22.5     1
62.0     1
38.5     1
Name: Age, Length: 80, dtype: int64

In [10]:
train['Age'] = train['Age'].fillna(impute_value)

In [11]:
test['Age'] = test['Age'].fillna(impute_value)

In [12]:
train['Age'].value_counts(dropna=True)

28.00    202
24.00     30
22.00     27
18.00     26
19.00     25
        ... 
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: Age, Length: 88, dtype: int64

In [13]:
test['Age'].value_counts(dropna=True)

28.0    93
24.0    17
21.0    17
22.0    16
30.0    15
        ..
76.0     1
28.5     1
22.5     1
62.0     1
38.5     1
Name: Age, Length: 79, dtype: int64

In [14]:
#Now we need to create a column "IsFemale"
train['IsFemale'] = (train['Sex'] == 'female').astype(int)

In [15]:
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [16]:
#then we decide on model variables and create numpy arrays
predictors : List[str] = ['Pclass', 'IsFemale', 'Age']

In [17]:
X_train = train[predictors].to_numpy()

In [32]:
X_test = train[predictors].to_numpy()

In [33]:
y_train = train['Survived'].to_numpy()

In [34]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [35]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [36]:
#Note: this is neither necessarily a good model nor engineered properly.
#we use the LogisticRegression from sklearn and create a model instance
from sklearn.linear_model import LogisticRegression

In [37]:
model = LogisticRegression()

In [38]:
model.fit(X_train, y_train)

LogisticRegression()

In [40]:
Y_predict = model.predict(X_test)

In [44]:
Y_predict[:10]

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1])

In [45]:
from sklearn.linear_model import LogisticRegressionCV

In [46]:
model_cv = LogisticRegressionCV(Cs=10)

In [47]:
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [48]:
#cross validation by hand with cross_val score
from sklearn.model_selection import cross_val_score

In [49]:
model = LogisticRegression(C=10)

In [50]:
scores = cross_val_score(model, X_train, y_train, cv=4)

In [51]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])